name: "git-cliff - Changelog Generator"
description: "Generate changelog based on your Git history"
inputs:
  version:
    description: "git-cliff version"
    required: false
    default: "latest"
  config:
    description: "config file location"
    required: false
    default: "cliff.toml"
  args:
    description: "git-cliff arguments"
    required: false
    default: "-v"
outputs:
  changelog:
    description: "output file"
  content:
    description: "content of the changelog"
  version:
    description: "version of the latest release"
runs:
  using: "composite"
  steps:
    - name: Download git-cliff
      shell: bash
      run: ${{ github.action_path }}/install.sh

    - name: Run git-cliff
      shell: bash
      run: ${{ github.action_path }}/run.sh

branding:
  icon: "triangle"
  color: "green"
